name: Deploy to Workshop

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: wiremod/gmod-upload@master
        with:
          id: 3137317907
          changelog: "Deployment via Github to commit ${GITHUB_SHA:0:7}"
        env:
          STEAM_USERNAME: ${{ secrets.WIRETEAM_WORKSHOP_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.WIRETEAM_WORKSHOP_PASSWORD }}